# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-30 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0004_observableproperty_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="observableproperty",
            name="name_en",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="observableproperty",
            name="name_fi",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="observableproperty",
            name="name_sv",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
