# Generated by Django 2.2.13 on 2020-08-14 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0008_use_explicit_base_manager_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="unit",
            field=models.ForeignKey(
                help_text="The unit the observation is about",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observation_history",
                to="services.Unit",
            ),
        ),
    ]
