# Generated by Django 5.2.14 on 2026-06-07 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0009_alter_observation_polymorphic_ctype"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasuredObservation",
            fields=[
                (
                    "observation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="observations.observation",
                    ),
                ),
                (
                    "measured_value",
                    models.FloatField(
                        blank=True,
                        help_text="The measured numeric value (e.g. water temperature in °C).",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("observations.observation",),
        ),
    ]
