# Generated by Django 5.2.13 on 2026-05-04 13:12

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    # Intentionally empty: reserve the initial users migration in production
    # before the real custom user model migrations are introduced.
    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop)
    ]
