# Generated by Django 5.2.13 on 2026-05-04 20:55

from django.db import migrations


def change_user_type(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    new_exists = ContentType.objects.filter(app_label="users", model="user").exists()
    ct = ContentType.objects.filter(app_label="auth", model="user").first()
    if not new_exists and ct:
        ct.app_label = "users"
        ct.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(change_user_type, migrations.RunPython.noop),
    ]
