# Generated by Django 5.2.13 on 2026-05-04 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_change_user_content_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
