# Generated by Django 5.2.13 on 2026-05-04 21:53
import uuid

from django.db import migrations, models


def populate_user_uuid(apps, schema_editor):
    User = apps.get_model("users", "User")

    for user in User.objects.filter(uuid__isnull=True).iterator():
        user.uuid = uuid.uuid4()
        user.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("helusers", "0002_add_oidcbackchannellogoutevent"),
        ("users", "0003_rename_user_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("id",)},
        ),
        migrations.AddField(
            model_name="user",
            name="ad_groups",
            field=models.ManyToManyField(blank=True, to="helusers.adgroup"),
        ),
        migrations.AddField(
            model_name="user",
            name="department_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_api_use",
            field=models.DateField(
                blank=True, null=True, verbose_name="Latest API token usage date"
            ),
        ),
        # Add uuid as a nullable field and initialize it like it would be if uuid
        # was missing value with helusers.AbstractUser.
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(populate_user_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(unique=True),
        ),
    ]
