# Generated by Django 3.2.7 on 2021-11-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mobility_data", "0002_mobileunit_extra"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gasfillingstationcontent",
            name="mobile_unit",
        ),
        migrations.RemoveField(
            model_name="contenttype",
            name="class_name",
        ),
        migrations.RemoveField(
            model_name="grouptype",
            name="class_name",
        ),
        migrations.DeleteModel(
            name="ChargingStationContent",
        ),
        migrations.DeleteModel(
            name="GasFillingStationContent",
        ),
    ]
