# Generated by Django 3.2.7 on 2021-11-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobility_data", "0006_auto_20211112_1312"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobileunit",
            name="name",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="mobileunit",
            name="name_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="mobileunit",
            name="name_fi",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="mobileunit",
            name="name_sv",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="mobileunitgroup",
            name="name",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="mobileunitgroup",
            name="name_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="mobileunitgroup",
            name="name_fi",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="mobileunitgroup",
            name="name_sv",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
