# Generated by Django 4.0 on 2022-02-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility_data', '0009_alter_contenttype_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileunit',
            name='unit_id',
            field=models.IntegerField(null=True, verbose_name='optional id to a unit in the servicemap, if id exist data is serialized from services_unit table'),
        ),
    ]
