# Generated by Django 4.0.4 on 2022-06-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mobility_data",
            "0015_add_contenttype_brush_salted_and_sanded_bicycle_network",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenttype",
            name="type_name",
            field=models.CharField(
                choices=[
                    ("CGS", "ChargingStation"),
                    ("GFS", "GasFillingStation"),
                    ("CRU", "CultureRouteUnit"),
                    ("CRG", "CultureRouteGeometry"),
                    ("BIS", "BicycleStand"),
                    ("PAZ", "PaymentZone"),
                    ("SLZ", "SpeedLimitZone"),
                    ("SPG", "ScooterParking"),
                    ("SSL", "ScooterSpeedLimit"),
                    ("SNP", "ScooterNoParking"),
                    ("APT", "AccessoryPublicToilet"),
                    ("ABH", "AccessoryBench"),
                    ("ATE", "AccessoryTable"),
                    ("AFG", "AccessoryFurnitureGroup"),
                    ("BSS", "BikeServiceStation"),
                    ("SCP", "ShareCarParkingPlace"),
                    ("BLB", "BrushSaltedBicycleNetwork"),
                    ("BND", "BrushSandedBicycleNetwork"),
                    ("GMA", "GuestMarina"),
                    ("BOK", "BoatParking"),
                    ("MAR", "Marina"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
