# Generated by Django 4.0.7 on 2022-11-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobility_data", "0027_add_content_type_nature_trail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenttype",
            name="type_name",
            field=models.CharField(
                choices=[
                    ("CGS", "ChargingStation"),
                    ("GFS", "GasFillingStation"),
                    ("CRU", "CultureRouteUnit"),
                    ("CRG", "CultureRouteGeometry"),
                    ("BIS", "BicycleStand"),
                    ("PAZ", "PaymentZone"),
                    ("SLZ", "SpeedLimitZone"),
                    ("SPG", "ScooterParking"),
                    ("SSL", "ScooterSpeedLimit"),
                    ("SNP", "ScooterNoParking"),
                    ("APT", "AccessoryPublicToilet"),
                    ("ABH", "AccessoryBench"),
                    ("ATE", "AccessoryTable"),
                    ("AFG", "AccessoryFurnitureGroup"),
                    ("BSS", "BikeServiceStation"),
                    ("SCP", "ShareCarParkingPlace"),
                    ("BLB", "BrushSaltedBicycleNetwork"),
                    ("BND", "BrushSandedBicycleNetwork"),
                    ("GMA", "GuestMarina"),
                    ("BOK", "BoatParking"),
                    ("MAR", "Marina"),
                    ("MSF", "MarinaSouthestFinalnd"),
                    ("NSP", "NoStaffParking"),
                    ("DSP", "DisabledParking"),
                    ("BER", "Berth"),
                    ("LUP", "LoadingUnloadingPlace"),
                    ("SWY", "Slipway"),
                    ("RCR", "RecreationalRoute"),
                    ("FYR", "FerryRoute"),
                    ("FGS", "FishingSpot"),
                    ("PPU", "PaavonPolku"),
                    ("FTL", "FitnessTrail"),
                    ("NTL", "NatureTrail"),
                    ("HTL", "HikingTrail"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
