# Generated by Django 4.0.7 on 2022-11-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobility_data", "0030_add_unique_constraint_to_content_and_group_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="type_name",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
