# Generated by Django 4.0.7 on 2022-11-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobility_data", "0031_increase_datasource_type_name_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenttype",
            name="type_name",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="grouptype",
            name="type_name",
            field=models.CharField(max_length=3, null=True),
        ),
    ]
