# Generated by Django 4.0.7 on 2022-12-08 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mobility_data", "0032_remove_choices_from_type_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contenttype",
            name="type_name",
        ),
    ]
