# Generated by Django 4.1.2 on 2023-02-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobility_data", "0034_remove_grouptype_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobileunit",
            name="content_types",
            field=models.ManyToManyField(
                related_name="mobile_units", to="mobility_data.contenttype"
            ),
        ),
    ]
