# Generated by Django 4.1.2 on 2023-02-08 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mobility_data", "0036_populate_mobile_type_content_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mobileunit",
            name="content_type",
        ),
    ]
