# Generated by Django 4.1.2 on 2023-02-08 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mobility_data", "0037_remove_mobileunit_content_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contenttype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="grouptype",
            options={"ordering": ["name"]},
        ),
    ]
