# Generated by Django 4.1.2 on 2023-03-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mobility_data",
            "0038_alter_contenttype_and_grouptype_ordering_to_field_name",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contenttype",
            options={"ordering": ["type_name"]},
        ),
        migrations.AlterModelOptions(
            name="grouptype",
            options={"ordering": ["type_name"]},
        ),
        migrations.RenameField(
            model_name="contenttype",
            old_name="name",
            new_name="type_name",
        ),
        migrations.RenameField(
            model_name="grouptype",
            old_name="name",
            new_name="type_name",
        ),
    ]
