# Generated by Django 4.1.2 on 2023-03-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobility_data", "0040_contenttype_name_grouptype_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenttype",
            name="description_en",
            field=models.TextField(
                null=True, verbose_name="Optional description of the content type."
            ),
        ),
        migrations.AddField(
            model_name="contenttype",
            name="description_fi",
            field=models.TextField(
                null=True, verbose_name="Optional description of the content type."
            ),
        ),
        migrations.AddField(
            model_name="contenttype",
            name="description_sv",
            field=models.TextField(
                null=True, verbose_name="Optional description of the content type."
            ),
        ),
        migrations.AddField(
            model_name="contenttype",
            name="name_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="contenttype",
            name="name_fi",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="contenttype",
            name="name_sv",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
