services:
  postgis:
    build: ./docker/postgres/
    platform: linux/x86_64
    restart: on-failure
    environment:
      - POSTGRES_USER=servicemap
      - POSTGRES_PASSWORD=servicemap
      - POSTGRES_DB=servicemap
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: servicemap-db

  django:
    build:
      context: .
      target: development
    env_file:
      - ./docker/django/.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - postgis
    container_name: servicemap-backend

volumes:
  pgdata:
    driver: local

networks:
  default:
    name: helsinki
