version: '3.8'
services:
    postgres:
        build: ./docker/postgres/
        environment:
            - POSTGRES_USER=servicemap
            - POSTGRES_PASSWORD=servicemap
            - POSTGRES_DB=servicemap
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgres/data 
    servicemap:
        build:
            context: ./
            dockerfile: ./Dockerfile
        command: start_django_development_server
        env_file:
            - config_dev.env
        volumes:
            - django-media:/var/media/
        ports:
            - "8000:8000"
        restart: on-failure
        depends_on:
            - postgres
    servicemap-ui:
        image: helsinki/servicemap-ui:staging
        ports:
            - "2048:2048"
        env_file:
            - config_dev_ui.env.example
        depends_on:
            - servicemap
volumes:
    postgres-data:
    django-media:
