version: '3.8'
services:
    postgres:
        build: ./docker/postgres/
        environment:
            - POSTGRES_USER=servicemap
            - POSTGRES_PASSWORD=servicemap
            - POSTGRES_DB=servicemap
        ports:
            - "5432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data 
            
    servicemap:
        build:
            context: ./
            dockerfile: ./Dockerfile
        environment:   
            - APPLY_MIGRATIONS=true
        command: start_django_development_server
        env_file:
            - config_dev.env
        volumes:
            - django-media:/var/media/
            - smbackend:/smbackend/
        ports:
            - "8000:8000"
        restart: on-failure
        depends_on:
            postgres:
                condition: service_started
    redis:
        image: redis        

    # celery:
    #     restart: always
    #     build:
    #         context: .
        
    #     command: celery -A smbackend worker -l INFO
    #     env_file:
    #         - config_dev.env
    #     volumes:
    #         - ./smbackend:/smbackend
    #     depends_on:
    #         - servicemap
    #         - redis
    #         - postgres


    # Todo, fix when Turku frontend has a working image
    # servicemap-ui:
    #     #image: helsinki/servicemap-ui:staging
    #     image: turku/servicemap-ui:staging
    #     ports:
    #         - "2048:2048"
    #     env_file:
    #         - config_dev_ui.env
    #     depends_on:
    #         - servicemap
volumes:
    postgres-data:
    django-media:
    smbackend:
