version: '3'
services:
    postgres:
        build: ./docker/postgres/
        environment:
            POSTGRES_USER: servicemap
            POSTGRES_PASSWORD: servicemap
            POSTGRES_DB: servicemap
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgres/data
        container_name: servicemap-db
    elasticsearch:
        image: helsinki/elasticsearch:1.7-ubuntu
        container_name: elasticsearch
        ports:
            - "9200:9200"
    servicemap:
        build:
            context: ./
            dockerfile: ./Dockerfile
        command: ./docker-entrypoint.sh
        environment:
            DATABASE_URL: postgis://servicemap:servicemap@servicemap-db/servicemap
        volumes:
            - .:/servicemap-src
            - django-media:/var/media/
        ports:
            - "8000:8000"
        depends_on:
            - postgres
            - elasticsearch
        container_name: servicemap-backend

volumes:
        postgres-data:
        django-media:
        elastic-data:
