version: '3'
services:
    postgres:
        build: ./docker/postgres/
        environment:
            POSTGRES_USER: servicemap
            POSTGRES_PASSWORD: servicemap
            POSTGRES_DB: servicemap
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgres/data
    elasticsearch:
        image: helsinki/elasticsearch:1.7-ubuntu
        volumes:
            - elastic-data:/var/lib/elasticsearch/elasticsearch
        ports:
            - "9200:9200"
    servicemap:
        build:
            context: ./
            dockerfile: ./Dockerfile
        command: ["./docker-entrypoint.sh" "start_django_development_server"]
        environment:
            APPLY_MIGRATIONS: true
            DATABASE_URL: postgis://servicemap:servicemap@postgres/servicemap
        volumes:
            - django-media:/var/media/
        ports:
            - "8000:8000"
        depends_on:
            - postgres
            - elasticsearch
volumes:
    postgres-data:
    django-media:
    elastic-data:
