sonar.projectKey=voneiden_smbackend
sonar.organization=voneiden
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.test.inclusions=**/tests/**/*
sonar.exclusions=**/migrations/*,pipelines/**/*
