# Generated by Django 2.2.13 on 2020-10-23 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0080_notification_add_external_url_title"),
        ("ptv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePTVIdentifier",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ptv_ids",
                        to="services.Service",
                    ),
                ),
            ],
        ),
    ]
