# Generated by Django 2.2.13 on 2020-09-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ptv", "0002_serviceptvidentifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitptvidentifier",
            name="source_municipality",
            field=models.IntegerField(null=True),
        ),
    ]
