# Generated by Django 4.0 on 2022-02-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IoTData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('source_name', models.CharField(choices=[('R24', 'Rent 24 Cars'), ('ISP', 'Infraroad Snow Plows')], default='R24', max_length=3)),
                ('data', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IoTDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=3, unique=True, verbose_name='Three letter long name for the source')),
                ('source_full_name', models.CharField(max_length=64, null=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
