# Generated by Django 4.0 on 2022-02-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IoTData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "source_name",
                    models.CharField(
                        choices=[("R24", "Rent24"), ("IRD", "InfraRoad")],
                        default="R24",
                        max_length=3,
                    ),
                ),
                ("data", models.JSONField(null=True)),
            ],
        ),
    ]
