# Generated by Django 4.0.2 on 2022-03-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iotdata',
            options={'ordering': ['-created']},
        ),
    ]
