# Generated by Django 4.1.13 on 2024-03-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0002_add_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="iotdatasource",
            name="headers",
            field=models.JSONField(
                blank=True, null=True, verbose_name="request headers"
            ),
        ),
    ]
