# Generated by Django 4.0.7 on 2022-10-06 06:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("street_maintenance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenancework",
            name="point",
        ),
        migrations.AddField(
            model_name="maintenancework",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                null=True, srid=4326
            ),
        ),
    ]
