# Generated by Django 4.0.7 on 2022-10-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("street_maintenance", "0002_rename_point_to_geometry_alter_to_geometryfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceunit",
            name="provider",
            field=models.CharField(
                choices=[("IFRAROAD", "Infraroad"), ("AUTORI", "Autori")],
                max_length=16,
                null=True,
            ),
        ),
    ]
