# Generated by Django 4.0.7 on 2022-10-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("street_maintenance", "0003_add_field_provider_to_maintenanceunit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenanceunit",
            name="unit_id",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
