# Generated by Django 4.0.7 on 2022-10-10 10:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("street_maintenance", "0004_alter_maintenanceunit_unit_id_to_charfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceunit",
            name="names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
    ]
