# Generated by Django 4.0.7 on 2022-10-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("street_maintenance", "0005_maintenanceunit_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenanceunit",
            name="provider",
            field=models.CharField(
                choices=[("INFRAROAD", "Infraroad"), ("AUTORI", "Autori")],
                max_length=16,
                null=True,
            ),
        ),
    ]
