# Generated by Django 4.0.7 on 2022-11-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("street_maintenance", "0006_fix_typo_in_maintenanceunit_provider_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenanceunit",
            name="provider",
            field=models.CharField(
                choices=[
                    ("INFRAROAD", "Infraroad"),
                    ("AUTORI", "Autori"),
                    ("KUNTEC", "Kuntec"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
