# Generated by Django 4.0.7 on 2022-12-09 11:39

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("street_maintenance", "0007_add_kuntec_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeometryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        null=True, srid=4326
                    ),
                ),
                (
                    "events",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("INFRAROAD", "Infraroad"),
                            ("AUTORI", "Autori"),
                            ("KUNTEC", "Kuntec"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
