# Generated by Django 4.0.7 on 2022-12-09 12:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("street_maintenance", "0008_geometryhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="geometryhistory",
            name="coordinates",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.FloatField(), size=None
                ),
                default=list,
                size=None,
            ),
        ),
    ]
