# Generated by Django 4.1.2 on 2022-12-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("street_maintenance", "0009_geometryhistory_add_coordinates_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geometryhistory",
            name="provider",
            field=models.CharField(
                choices=[
                    ("INFRAROAD", "Infraroad"),
                    ("AUTORI", "Autori"),
                    ("KUNTEC", "Kuntec"),
                    ("DESTIA", "Destia"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceunit",
            name="provider",
            field=models.CharField(
                choices=[
                    ("INFRAROAD", "Infraroad"),
                    ("AUTORI", "Autori"),
                    ("KUNTEC", "Kuntec"),
                    ("DESTIA", "Destia"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
