# Generated by Django 4.1.2 on 2023-01-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("street_maintenance", "0010_add_destia_to_provider_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geometryhistory",
            name="provider",
            field=models.CharField(
                choices=[
                    ("INFRAROAD", "Infraroad"),
                    ("YIT", "YIT"),
                    ("KUNTEC", "Kuntec"),
                    ("DESTIA", "Destia"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceunit",
            name="provider",
            field=models.CharField(
                choices=[
                    ("INFRAROAD", "Infraroad"),
                    ("YIT", "YIT"),
                    ("KUNTEC", "Kuntec"),
                    ("DESTIA", "Destia"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
