# Generated by Django 3.2.7 on 2021-11-19 11:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle_network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleNetworkSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_network', models.FileField(upload_to='media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bicyclenetwork',
            name='main_network',
        ),
        migrations.AddField(
            model_name='bicyclenetwork',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='BicyceNetworkPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField(null=True)),
                ('pituus', models.FloatField(null=True)),
                ('guid', models.CharField(max_length=64, null=True)),
                ('oid_tunnus', models.FloatField(null=True)),
                ('ketju_oid', models.FloatField(null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=3067)),
                ('bicycle_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_part', to='bicycle_network.bicyclenetwork')),
            ],
        ),
    ]
