# Generated by Django 3.2.7 on 2021-11-23 09:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bicycle_network", "0005_auto_20211123_0948"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bicyclenetworkpart",
            name="fid",
        ),
        migrations.RemoveField(
            model_name="bicyclenetworkpart",
            name="guid",
        ),
        migrations.RemoveField(
            model_name="bicyclenetworkpart",
            name="ketju_oid",
        ),
        migrations.RemoveField(
            model_name="bicyclenetworkpart",
            name="oid_tunnus",
        ),
        migrations.RemoveField(
            model_name="bicyclenetworkpart",
            name="pituus",
        ),
        migrations.AddField(
            model_name="bicyclenetwork",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                null=True, srid=3067
            ),
        ),
        migrations.AddField(
            model_name="bicyclenetworkpart",
            name="TKU_toiminnall_pp",
            field=models.FloatField(null=True, verbose_name="Functional class"),
        ),
        migrations.AddField(
            model_name="bicyclenetworkpart",
            name="liikennevi",
            field=models.FloatField(null=True, verbose_name="Direction of trafic flow"),
        ),
        migrations.AddField(
            model_name="bicyclenetworkpart",
            name="teksti",
            field=models.CharField(
                max_length=64, null=True, verbose_name="Name of the street (in Finnish)"
            ),
        ),
        migrations.AddField(
            model_name="bicyclenetworkpart",
            name="tienimi2",
            field=models.CharField(
                max_length=64, null=True, verbose_name="Name of the street (in Swedish)"
            ),
        ),
        migrations.AddField(
            model_name="bicyclenetworkpart",
            name="toiminaall",
            field=models.FloatField(null=True, verbose_name="Functional class"),
        ),
        migrations.AlterField(
            model_name="bicyclenetworkpart",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                null=True,
                srid=3067,
                verbose_name="Functional class of cycle or pedestrian path",
            ),
        ),
    ]
