# Generated by Django 3.2.7 on 2021-11-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle_network', '0009_auto_20211123_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicyclenetwork',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='bicyclenetworkpart',
            name='TKU_toiminnall_pp',
            field=models.IntegerField(null=True, verbose_name='Functional class of cycle or pedestrian path'),
        ),
        migrations.AlterField(
            model_name='bicyclenetworkpart',
            name='liikennevi',
            field=models.IntegerField(null=True, verbose_name='Direction of trafic flow'),
        ),
        migrations.AlterField(
            model_name='bicyclenetworkpart',
            name='toiminnall',
            field=models.IntegerField(null=True, verbose_name='Functional class'),
        ),
    ]
