# Generated by Django 4.1.13 on 2024-06-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("munigeo", "0016_address_modified_at_remove_auto_now"),
        ("exceptional_situations", "0002_alter_situationannouncement_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="situationannouncement",
            name="municipalities",
            field=models.ManyToManyField(to="munigeo.municipality"),
        ),
    ]
