# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 03:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0012_unit_accessibility_sentence_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="accessibility_viewpoints",
            field=django.contrib.postgres.fields.jsonb.JSONField(default="{}"),
        ),
    ]
