# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_unit_accessibility_viewpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField()),
                ('filter', models.TextField(blank=True, default='', null=True)),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceTreeNode')),
            ],
        ),
    ]
