# Generated by Django 1.11.1 on 2017-05-11 23:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0015_auto_20170512_0132"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ServiceTreeNode",
            new_name="OntologyTreeNode",
        ),
    ]
