# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0019_auto_20170514_1612"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization", old_name="object_identifier", new_name="oid",
        ),
    ]
