# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20170516_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='object_identifier',
            new_name='oid',
        ),
    ]
