# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_auto_20170516_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='short_desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='short_desc_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='short_desc_sv',
            field=models.TextField(null=True),
        ),
    ]
