# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0023_auto_20170516_1838"),
    ]

    operations = [
        migrations.RemoveField(model_name="unit", name="description",),
    ]
