# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_make_department_hierarchical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='root_services',
        ),
    ]
