# Generated by Django 1.11.1 on 2017-06-06 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0027_remove_unit_root_services"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="extra_searchwords",
        ),
    ]
