# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_remove_unit_extra_searchwords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['id']},
        ),
    ]
