# Generated by Django 1.11.1 on 2017-06-27 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0029_order_units_by_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unit",
            options={"ordering": ["-pk"]},
        ),
    ]
