# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_remove_unit_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='call_charge_info_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='call_charge_info_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='call_charge_info_sv',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
