# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0034_make_organizer_type_choicefield"),
        ("services", "0030_restore_origin_last_modified_field"),
    ]

    operations = []
