# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0036_unit_contract_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ontologytreenode", options={"ordering": ["-pk"]},
        ),
        migrations.AlterModelOptions(
            name="ontologyword", options={"ordering": ["-pk"]},
        ),
    ]
