# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_add_ordering_to_ontologymodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(db_index=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name_en',
            field=models.CharField(db_index=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name_fi',
            field=models.CharField(db_index=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name_sv',
            field=models.CharField(db_index=True, max_length=220, null=True),
        ),
    ]
