# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_unit_ontologyword_details_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitontologyworddetails',
            name='clarification_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='unitontologyworddetails',
            name='clarification_fi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='unitontologyworddetails',
            name='clarification_sv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
