# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0043_fix_ontologyworddetails_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="ontologyword",
            name="clarification_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ontologyword",
            name="period_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
