# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0044_add_ontologyword_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="ontologytreenode",
            name="related_ontologywords",
            field=models.ManyToManyField(to="services.OntologyWord"),
        ),
    ]
