# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_change_org_to_dept'),
        ('services', '0045_ontologytreenode_related_ontologywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
