# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0048_rename_ontologyword_to_service"),
    ]

    operations = [
        migrations.RenameField(
            model_name="unit",
            old_name="root_servicenodes",
            new_name="root_service_nodes",
        ),
    ]
