# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0050_sane_data_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessibilitysentence',
            name='unit',
        ),
        migrations.DeleteModel(
            name='AccessibilitySentence',
        ),
    ]
