# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0051_remove_accessibility_sentences"),
    ]

    operations = [
        migrations.RemoveField(model_name="unit", name="accessibility_sentence_hash",),
    ]
