# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('munigeo', '0005_auto_20180109_1052'),
        ('services', '0052_remove_unit_accessibility_sentence_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='munigeo.Municipality'),
        ),
    ]
