# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0054_rename_last_modified_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="unit",
            old_name="desc",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="unit",
            old_name="desc_en",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="unit",
            old_name="desc_fi",
            new_name="description_fi",
        ),
        migrations.RenameField(
            model_name="unit",
            old_name="desc_sv",
            new_name="description_sv",
        ),
        migrations.RenameField(
            model_name="unit",
            old_name="short_desc",
            new_name="short_description",
        ),
        migrations.RenameField(
            model_name="unit",
            old_name="short_desc_en",
            new_name="short_description_en",
        ),
        migrations.RenameField(
            model_name="unit",
            old_name="short_desc_fi",
            new_name="short_description_fi",
        ),
        migrations.RenameField(
            model_name="unit",
            old_name="short_desc_sv",
            new_name="short_description_sv",
        ),
    ]
