# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 15:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0055_rename_unit_description_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='accessibility_viewpoints',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}', null=True),
        ),
    ]
