# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-18 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0059_add_unit_count_related_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='divisions',
        ),
    ]
