# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-18 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0060_remove_unit_divisions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='hierarchy_level',
        ),
    ]
