# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-24 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0061_remove_department_hierarchy_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="root_department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descendant_units",
                to="services.Department",
            ),
        ),
    ]
