# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-29 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0062_unit_root_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitconnection",
            name="name",
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name="unitconnection",
            name="name_en",
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="unitconnection",
            name="name_fi",
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="unitconnection",
            name="name_sv",
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="unitconnection",
            name="section_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "PHONE_OR_EMAIL"),
                    (2, "LINK"),
                    (3, "TOPICAL"),
                    (4, "OTHER_INFO"),
                    (5, "OPENING_HOURS"),
                    (6, "SOCIAL_MEDIA_LINK"),
                    (7, "OTHER_ADDRESS"),
                    (8, "HIGHLIGHT"),
                    (9, "ESERVICE_LINK"),
                ],
                null=True,
            ),
        ),
    ]
