# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0064_increase_unit_organizer_name_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='phone',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
