# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-09 12:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0066_service_root_service_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='extensions',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
