# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-08 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0067_unit_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenodeunitcount',
            name='city_as_department',
            field=models.UUIDField(null=True),
        ),
    ]
