# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 08:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0068_unitaccessibilityshortcomings"),
    ]

    operations = [
        migrations.RemoveField(model_name="unitaccessibilityshortcomings", name="id",),
        migrations.AlterField(
            model_name="unitaccessibilityshortcomings",
            name="accessibility_description",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AlterField(
            model_name="unitaccessibilityshortcomings",
            name="accessibility_shortcoming_count",
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
        migrations.AlterField(
            model_name="unitaccessibilityshortcomings",
            name="unit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="accessibility_shortcomings",
                serialize=False,
                to="services.Unit",
            ),
        ),
    ]
