# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-07 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0072_make_department_oid_field_longer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="oid",
            field=models.TextField(null=True),
        ),
    ]
