# Generated by Django 2.2.12 on 2020-05-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0073_remove_length_limitation_department_oid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="root_service_nodes",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
