# Generated by Django 2.2.13 on 2020-08-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0075_update_jsonfield_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="call_charge_info",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="call_charge_info_en",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="call_charge_info_fi",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="call_charge_info_sv",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
