# Generated by Django 2.2.13 on 2020-08-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0076_update_call_charge_info_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted at"
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
