# Generated by Django 2.2.13 on 2020-10-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0077_unit_soft_delete"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("title_fi", models.CharField(blank=True, max_length=100, null=True)),
                ("title_sv", models.CharField(blank=True, max_length=100, null=True)),
                ("title_en", models.CharField(blank=True, max_length=100, null=True)),
                ("content", models.TextField()),
                ("content_fi", models.TextField(null=True)),
                ("content_sv", models.TextField(null=True)),
                ("content_en", models.TextField(null=True)),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        help_text="Only active objects are visible in the API.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ErrorMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("title_fi", models.CharField(blank=True, max_length=100, null=True)),
                ("title_sv", models.CharField(blank=True, max_length=100, null=True)),
                ("title_en", models.CharField(blank=True, max_length=100, null=True)),
                ("content", models.TextField()),
                ("content_fi", models.TextField(null=True)),
                ("content_sv", models.TextField(null=True)),
                ("content_en", models.TextField(null=True)),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        help_text="Only active objects are visible in the API.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
