# Generated by Django 3.1.5 on 2021-01-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0080_notification_add_external_url_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="level",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="department",
            name="lft",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="department",
            name="rght",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="servicenode",
            name="level",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="servicenode",
            name="lft",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="servicenode",
            name="rght",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="unit",
            name="accessibility_viewpoints",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="unitaccessibilityshortcomings",
            name="accessibility_description",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name="unitaccessibilityshortcomings",
            name="accessibility_shortcoming_count",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
