# Generated by Django 3.1.6 on 2021-02-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0081_django3_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="contract_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "private_contract_school"),
                    (1, "municipal_service"),
                    (2, "private_service"),
                    (3, "purchased_service"),
                    (4, "service_by_joint_municipal_authority"),
                    (5, "service_by_municipal_group_entity"),
                    (6, "service_by_municipally_owned_company"),
                    (7, "service_by_other_municipality"),
                    (8, "service_by_regional_cooperation_organization"),
                    (9, "state_service"),
                    (10, "supported_operations"),
                    (11, "voucher_service"),
                    (12, "state_contract_school"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Poistettu-aikaleima"
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktiivinen"),
        ),
    ]
