# Generated by Django 3.1.7 on 2021-02-26 08:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0082_update_unit_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitEntrance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_main_entrance", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=600)),
                ("name_fi", models.CharField(max_length=600, null=True)),
                ("name_sv", models.CharField(max_length=600, null=True)),
                ("name_en", models.CharField(max_length=600, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        null=True, srid=3067
                    ),
                ),
                ("picture_url", models.URLField(max_length=600, null=True)),
                ("streetview_url", models.URLField(max_length=600, null=True)),
                ("created_time", models.DateTimeField(null=True)),
                (
                    "last_modified_time",
                    models.DateTimeField(
                        db_index=True, help_text="Time of last modification"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrances",
                        to="services.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["-pk", "-is_main_entrance"],
            },
        ),
    ]
