# Generated by Django 3.2.7 on 2021-10-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0083_unitentrance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
