# Generated by Django 3.2.10 on 2021-12-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0084_alter_unitconnection_section_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="extra",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
