# Generated by Django 3.2.7 on 2021-11-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0084_auto_20211012_1241"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="extra",
            field=models.JSONField(null=True),
        ),
    ]
