# Generated by Django 3.2.11 on 2022-01-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0085_unit_extra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitconnection",
            name="name",
            field=models.CharField(max_length=2100),
        ),
        migrations.AlterField(
            model_name="unitconnection",
            name="name_en",
            field=models.CharField(max_length=2100, null=True),
        ),
        migrations.AlterField(
            model_name="unitconnection",
            name="name_fi",
            field=models.CharField(max_length=2100, null=True),
        ),
        migrations.AlterField(
            model_name="unitconnection",
            name="name_sv",
            field=models.CharField(max_length=2100, null=True),
        ),
    ]
