# Generated by Django 4.0 on 2022-01-27 09:32

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0086_unit_related_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='search_column',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='search_column',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='related_units',
            field=models.ManyToManyField(blank=True, to='services.Unit'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_column'], name='services_se_search__756b22_gin'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_column'], name='services_un_search__ce83d4_gin'),
        ),
    ]
