# Generated by Django 3.2.10 on 2022-01-10 12:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0086_update_unitconnection_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="search_column",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="search_column",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="service",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_column"], name="services_se_search__756b22_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_column"], name="services_un_search__ce83d4_gin"
            ),
        ),
    ]
