# Generated by Django 3.2.7 on 2021-12-21 12:51

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0086_unit_related_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200)),
                ('vector_column', django.contrib.postgres.search.SearchVectorField()),
            ],
            options={
                'db_table': 'search_view',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='service',
            name='vector_column',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='servicenode',
            name='vector_column',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='vector_column',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='service',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vector_column'], name='services_se_vector__15a5d6_gin'),
        ),
        migrations.AddIndex(
            model_name='servicenode',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vector_column'], name='services_se_vector__f4f534_gin'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vector_column'], name='services_un_vector__c5816c_gin'),
        ),
    ]
