# Generated by Django 3.2.10 on 2022-01-10 12:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0086_update_unitconnection_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchView",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=200)),
                ("search_column", django.contrib.postgres.search.SearchVectorField()),
            ],
            options={
                "db_table": "search_view",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="service",
            name="search_column",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="servicenode",
            name="search_column",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="search_column",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="service",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_column"], name="services_se_search__756b22_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="servicenode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_column"], name="services_se_search__d288ae_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_column"], name="services_un_search__ce83d4_gin"
            ),
        ),
    ]
