# Generated by Django 4.0.2 on 2022-04-08 04:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0093_combine_servicenodes_with_same_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="syllables_fi",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=16), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="servicenode",
            name="syllables_fi",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=16), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="syllables_fi",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=16), default=list, size=None
            ),
        ),
    ]
