# Generated by Django 4.1.7 on 2023-07-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0095_exclusionrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitconnection",
            name="section_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "PHONE_OR_EMAIL"),
                    (2, "LINK"),
                    (3, "TOPICAL"),
                    (4, "OTHER_INFO"),
                    (5, "OPENING_HOURS"),
                    (6, "SOCIAL_MEDIA_LINK"),
                    (7, "OTHER_ADDRESS"),
                    (8, "HIGHLIGHT"),
                    (9, "ESERVICE_LINK"),
                    (10, "PRICE"),
                ],
                null=True,
            ),
        ),
    ]
