# Generated by Django 4.1.7 on 2023-07-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0096_alter_unitconnection_section_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitconnection",
            name="name",
            field=models.CharField(max_length=2100),
        ),
        migrations.AlterField(
            model_name="unitconnection",
            name="name_en",
            field=models.CharField(max_length=2100, null=True),
        ),
        migrations.AlterField(
            model_name="unitconnection",
            name="name_fi",
            field=models.CharField(max_length=2100, null=True),
        ),
        migrations.AlterField(
            model_name="unitconnection",
            name="name_sv",
            field=models.CharField(max_length=2100, null=True),
        ),
    ]
