# Generated by Django 4.1 on 2022-08-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0098_unitconnection_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="outdoor_sports_map_usage",
            field=models.BooleanField(
                default=False,
                help_text="Intented for outdoor sports map usage",
                verbose_name="Outdoor sports map usage",
            ),
        ),
        migrations.AddField(
            model_name="errormessage",
            name="outdoor_sports_map_usage",
            field=models.BooleanField(
                default=False,
                help_text="Intented for outdoor sports map usage",
                verbose_name="Outdoor sports map usage",
            ),
        ),
    ]
