# Generated by Django 4.1.7 on 2023-07-21 07:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0098_alter_unitconnection_section_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitconnection",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
