# Generated by Django 4.1.13 on 2024-05-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0100_alter_unitconnection_section_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExclusionWord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100, verbose_name="Word")),
                (
                    "language_short",
                    models.CharField(max_length=2, verbose_name="Language short"),
                ),
            ],
            options={
                "verbose_name": "Exclusion word",
                "verbose_name_plural": "Exclusion words",
                "ordering": ["-id"],
            },
        ),
    ]
