# Generated by Django 4.1.2 on 2022-11-08 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0102_requeststatistic"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackMapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abbr_fi",
                    models.CharField(max_length=10, verbose_name="Abbreviation (fi)"),
                ),
                (
                    "service_code",
                    models.CharField(
                        default="2809", max_length=10, verbose_name="Service code"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_fi", models.CharField(max_length=100, null=True)),
                ("name_sv", models.CharField(max_length=100, null=True)),
                ("name_en", models.CharField(max_length=100, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.department",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_feedback_mappings",
                        to="services.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback mapping",
                "verbose_name_plural": "Feedback mappings",
                "ordering": ["-id"],
                "unique_together": {("service_code", "department")},
            },
        ),
    ]
