# Generated by Django 4.1.3 on 2022-11-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0103_feedbackmapping"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="contract_type",
        ),
        migrations.AddField(
            model_name="unit",
            name="displayed_service_owner",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="displayed_service_owner_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="displayed_service_owner_fi",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="displayed_service_owner_sv",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="displayed_service_owner_type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="vtj_prt",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="vtj_prt_verified",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
