# Generated by Django 4.1.7 on 2023-03-21 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0107_organizationserviceunitcount"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationServiceNodeUnitCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField()),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.department",
                    ),
                ),
                (
                    "service_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_count_organizations",
                        to="services.servicenode",
                    ),
                ),
            ],
            options={
                "unique_together": {("service_node", "organization")},
            },
        ),
    ]
