# Generated by Django 4.1.7 on 2023-07-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0108_organizationservicenodeunitcount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
