# Generated by Django 4.1.7 on 2023-07-12 07:43

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("munigeo", "0014_increase_origin_id_length"),
        ("services", "0109_alter_unit_deleted_at_and_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobilityServiceNode",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("name_fi", models.CharField(db_index=True, max_length=200, null=True)),
                ("name_sv", models.CharField(db_index=True, max_length=200, null=True)),
                ("name_en", models.CharField(db_index=True, max_length=200, null=True)),
                ("service_reference", models.TextField(null=True)),
                (
                    "last_modified_time",
                    models.DateTimeField(
                        db_index=True, help_text="Time of last modification"
                    ),
                ),
                (
                    "search_column_fi",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "search_column_sv",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "search_column_en",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "syllables_fi",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16),
                        default=list,
                        size=None,
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                ("keywords", models.ManyToManyField(to="services.keyword")),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="services.mobilityservicenode",
                    ),
                ),
                ("related_services", models.ManyToManyField(to="services.service")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MobilityOrganizationServiceNodeUnitCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField()),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.department",
                    ),
                ),
                (
                    "service_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_count_organizations",
                        to="services.mobilityservicenode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MobilityServiceNodeUnitCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField()),
                (
                    "division",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="munigeo.administrativedivision",
                    ),
                ),
                (
                    "division_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="munigeo.administrativedivisiontype",
                    ),
                ),
                (
                    "service_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_counts",
                        to="services.mobilityservicenode",
                    ),
                ),
            ],
            options={
                "unique_together": {("service_node", "division")},
            },
        ),
        migrations.AddIndex(
            model_name="mobilityservicenode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_column_fi"], name="services_mo_search__af3666_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="mobilityservicenode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_column_sv"], name="services_mo_search__bf9960_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="mobilityservicenode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_column_en"], name="services_mo_search__15b23d_gin"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mobilityorganizationservicenodeunitcount",
            unique_together={("service_node", "organization")},
        ),
    ]
