# Generated by Django 4.1.7 on 2023-08-23 05:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0111_unit_mobility_service_nodes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mobilityorganizationservicenodeunitcount",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="mobilityorganizationservicenodeunitcount",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="mobilityorganizationservicenodeunitcount",
            name="service_node",
        ),
        migrations.AlterUniqueTogether(
            name="mobilityservicenodeunitcount",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="mobilityservicenodeunitcount",
            name="division",
        ),
        migrations.RemoveField(
            model_name="mobilityservicenodeunitcount",
            name="division_type",
        ),
        migrations.RemoveField(
            model_name="mobilityservicenodeunitcount",
            name="service_node",
        ),
        migrations.RemoveIndex(
            model_name="mobilityservicenode",
            name="services_mo_search__af3666_gin",
        ),
        migrations.RemoveIndex(
            model_name="mobilityservicenode",
            name="services_mo_search__bf9960_gin",
        ),
        migrations.RemoveIndex(
            model_name="mobilityservicenode",
            name="services_mo_search__15b23d_gin",
        ),
        migrations.RemoveField(
            model_name="mobilityservicenode",
            name="keywords",
        ),
        migrations.RemoveField(
            model_name="mobilityservicenode",
            name="related_services",
        ),
        migrations.RemoveField(
            model_name="mobilityservicenode",
            name="search_column_en",
        ),
        migrations.RemoveField(
            model_name="mobilityservicenode",
            name="search_column_fi",
        ),
        migrations.RemoveField(
            model_name="mobilityservicenode",
            name="search_column_sv",
        ),
        migrations.RemoveField(
            model_name="mobilityservicenode",
            name="syllables_fi",
        ),
        migrations.DeleteModel(
            name="MobilityOrganizationServiceNodeUnitCount",
        ),
        migrations.DeleteModel(
            name="MobilityServiceNodeUnitCount",
        ),
    ]
