# Generated by Django 4.1.7 on 2023-10-11 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("munigeo", "0014_increase_origin_id_length"),
        ("services", "0112_alter_mobilityservicenode"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobilityServiceNodeUnitCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField()),
                (
                    "division",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="munigeo.administrativedivision",
                    ),
                ),
                (
                    "division_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="munigeo.administrativedivisiontype",
                    ),
                ),
                (
                    "mobility_service_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_counts",
                        to="services.mobilityservicenode",
                    ),
                ),
            ],
            options={
                "unique_together": {("mobility_service_node", "division")},
            },
        ),
    ]
