# Generated by Django 4.2.6 on 2023-10-26 10:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0114_delete_organizationservicenodeunitcount"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="geometry_3d",
            field=django.contrib.gis.db.models.fields.GeometryField(
                dim=3, null=True, srid=3067
            ),
        ),
    ]
