# Generated by Django 5.0.1 on 2024-02-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0115_unit_geometry_3d"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="address_postal_full",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="address_postal_full_en",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="address_postal_full_fi",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="address_postal_full_sv",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="email",
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="fax",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="phone",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="picture_url",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="www",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="www_en",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="www_fi",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="www_sv",
            field=models.URLField(max_length=500, null=True),
        ),
    ]
