# Generated by Django 5.1.11 on 2025-09-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0117_exclusionword"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="servicenode",
            index=models.Index(
                fields=["tree_id", "lft"], name="services_servicenode_tree_fc8f"
            ),
        ),
    ]
