# Generated by Django 5.2.13 on 2026-05-05 11:25

from django.db import migrations, models
from django.db.models import Count, Sum


def deduplicate_request_statistics(apps, schema_editor):
    RequestStatistic = apps.get_model("services", "RequestStatistic")

    duplicate_timeframes = (
        RequestStatistic.objects.values("timeframe")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
        .values_list("timeframe", flat=True)
    )

    for timeframe in duplicate_timeframes:
        qs = RequestStatistic.objects.filter(timeframe=timeframe)
        total = qs.aggregate(total=Sum("request_counter"))["total"]
        total_details = {"embed": 0, "mobile_device": 0}
        for details in qs.values_list("details", flat=True):
            for key in total_details:
                total_details[key] += details.get(key, 0)
        winner = qs.order_by("id").first()
        qs.exclude(id=winner.id).delete()
        winner.request_counter = total
        winner.details = total_details
        winner.save()


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0120_set_manual_maintenance_organization"),
    ]

    operations = [
        migrations.RunPython(deduplicate_request_statistics, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="requeststatistic",
            name="timeframe",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Timeframe"
            ),
        ),
    ]
