FROM python:3.6

WORKDIR /opt/smbackend

COPY . /opt/smbackend

EXPOSE 8000

# Joe & less for debugging convenience
RUN apt-get update && apt-get install -y joe less && apt-get install -y libgdal20 && cp deploy/django_local_settings_docker.py local_settings.py

COPY . .

RUN pip install --no-cache-dir -r deploy/requirements.txt

CMD deploy/server.sh

