# Generated by Django 4.0.7 on 2022-08-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eco_counter", "0004_add_name_en_name_fi_station_name_sv_to_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="importstate",
            name="csv_data_source",
            field=models.CharField(
                choices=[("TC", "TrafficCount"), ("EC", "EcoCounter")],
                default="EC",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="csv_data_source",
            field=models.CharField(
                choices=[("TC", "TrafficCount"), ("EC", "EcoCounter")],
                default="EC",
                max_length=2,
            ),
        ),
    ]
