# Generated by Django 4.0.7 on 2022-08-25 17:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eco_counter",
            "0006_alter_importstate_csv_data_source_and_current_year_number",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="daydata",
            name="value_bk",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="daydata",
            name="value_bp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="daydata",
            name="value_bt",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="hourdata",
            name="values_bk",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="hourdata",
            name="values_bp",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="hourdata",
            name="values_bt",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="monthdata",
            name="value_bk",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthdata",
            name="value_bp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthdata",
            name="value_bt",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weekdata",
            name="value_bk",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weekdata",
            name="value_bp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weekdata",
            name="value_bt",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="yeardata",
            name="value_bk",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="yeardata",
            name="value_bp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="yeardata",
            name="value_bt",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="importstate",
            name="current_year_number",
            field=models.PositiveSmallIntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name="year",
            name="year_number",
            field=models.PositiveSmallIntegerField(default=2022),
        ),
    ]
