# Generated by Django 4.0.7 on 2022-09-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eco_counter", "0008_remove_importstate_rows_imported"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importstate",
            name="csv_data_source",
            field=models.CharField(
                choices=[
                    ("TC", "TrafficCounter"),
                    ("EC", "EcoCounter"),
                    ("LC", "LamCounter"),
                ],
                default="EC",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="csv_data_source",
            field=models.CharField(
                choices=[
                    ("TC", "TrafficCounter"),
                    ("EC", "EcoCounter"),
                    ("LC", "LamCounter"),
                ],
                default="EC",
                max_length=2,
            ),
        ),
    ]
