# Generated by Django 4.0.7 on 2022-09-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eco_counter",
            "0009_add_lam_counter_csv_data_source_to_station_and_importstate",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="station",
            name="name_en",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="name_fi",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="name_sv",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
