# Generated by Django 4.1.2 on 2023-01-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_counter", "0011_add_lam_id_to_station"),
    ]

    operations = [
        migrations.AlterField(
            model_name="year",
            name="year_number",
            field=models.PositiveSmallIntegerField(default=2023),
        ),
    ]
