# Generated by Django 4.1.2 on 2023-02-15 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eco_counter", "0012_set_static_default_year_year_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importstate",
            name="current_month_number",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="importstate",
            name="current_year_number",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
