# Generated by Django 4.2 on 2023-05-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eco_counter", "0014_remove_station_lam_id_station_station_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importstate",
            name="csv_data_source",
            field=models.CharField(
                choices=[
                    ("TC", "TrafficCounter"),
                    ("EC", "EcoCounter"),
                    ("LC", "LamCounter"),
                    ("TR", "TelraamCounter"),
                    ("TV", "TelraamCSV"),
                ],
                default="EC",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="csv_data_source",
            field=models.CharField(
                choices=[
                    ("TC", "TrafficCounter"),
                    ("EC", "EcoCounter"),
                    ("LC", "LamCounter"),
                    ("TR", "TelraamCounter"),
                    ("TV", "TelraamCSV"),
                ],
                default="EC",
                max_length=2,
            ),
        ),
    ]
