# Generated by Django 4.2 on 2023-05-22 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "eco_counter",
            "0015_add_telraam_counter_and_traffic_csv_choice_to_importstate",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="importstate",
            name="current_day_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
    ]
