# Generated by Django 4.2 on 2023-05-24 06:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eco_counter", "0016_add_importstate_current_day_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="station",
            old_name="geom",
            new_name="location",
        ),
    ]
