# Generated by Django 4.1.10 on 2024-01-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_counter", "0018_add_geometry_to_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="data_from_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="data_until_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
