# Generated by Django 4.1.10 on 2024-01-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_counter", "0020_station_sensor_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="is_active",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
