# Generated by Django 4.1.13 on 2024-07-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eco_counter", "0021_station_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="day",
            name="station",
        ),
        migrations.RemoveField(
            model_name="month",
            name="station",
        ),
        migrations.RemoveField(
            model_name="week",
            name="station",
        ),
        migrations.RemoveField(
            model_name="year",
            name="station",
        ),
    ]
