# Generated by Django 4.1.13 on 2024-07-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "eco_counter",
            "0022_remove_day_station_remove_month_station_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monthdata",
            options={"ordering": ["-month__year__year_number", "-month__month_number"]},
        ),
        migrations.RemoveField(
            model_name="monthdata",
            name="year",
        ),
    ]
