name: Continuous Integration
on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop. master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgis://postgres:postgres@localhost/smbackend
      SECRET_KEY: test-secret
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install required Ubuntu packages
      run: |
        sudo apt-get install gdal-bin
    - name: Create needed postgis extensions
      run: |
        psql -h localhost -U postgres template1 -c 'create extension hstore;'
    - name: Install PyPI dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Python side code neatness tests
      run: |
        flake8
        black --check .
        isort . -c
    - name: Run pytest code functionality tests
      run: |
        pytest --cov=.
    services:
      postgres:
        image: postgis/postgis:11-2.5
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
